const coctelesArray = [
  {
    'id':1,
    'nombre': "Cafe irlandes",
    'precio': 300,
    'tipo': "sobremesa",
    'imagen': "./imagenes/cocteles/cafe-irlandes.jpg",
    'origen': "Irlanda",
    'descripcion': "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus, placeat?",
  },
    {
    'id':2,
    'nombre': "Julepe de menta",
    'precio': 200,
    'tipo': "sobremesa",
    'imagen': "./imagenes/cocteles/mint-julep.jpg",
    'origen': "Estados Unidos",
    'descripcion': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea, pariatur.",
  },
    {
    'id':3,
    'nombre': "Grasshopper",
    'precio': 350,
    'tipo': "sobremesa",
    'imagen': "./imagenes/cocteles/grasshopper.jpg",
    'origen': "Estados Unidos",
    'descripcion':"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, nihil.",
  },
    {
    'id':4,
    'nombre': "Spritz",
    'precio': 400,
    'tipo': "aperitivo",
    'imagen': "./imagenes/cocteles/spritz.jpg",
    'origen': "Italia",
    'descripcion':"Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, voluptatum.",
  },
    {
    'id':5,
    'nombre': "Negroni",
    'precio': 375,
    'tipo': "aperitivo",
    'imagen': "./imagenes/cocteles/negroni.jpg",
    'origen': "Italia",
    'descripcion':"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, corrupti?",
  },
    {
    'id':6,
    'nombre': "Hesperidina",
    'precio': 325,
    'tipo': "aperitivo",
    'imagen': "./imagenes/cocteles/hesperidina.jpg",
    'origen': "Argentina",
    'descripcion':"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit, temporibus.",
  },
    {
    'id':7,
    'nombre': "Mojito",
    'precio': 250,
    'tipo': "digestivo",
    'imagen': "./imagenes/cocteles/mojito.jpg",
    'origen': "Cuba",
    'descripcion':"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Impedit, consequuntur.",
  },
    {
    'id':8,
    'nombre': "Fernet",
    'precio': 300,
    'tipo': "digestivo",
    'imagen': "./imagenes/cocteles/fernet.jpg",
    'origen': "Italia",
    'descripcion':"Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, qui.",
  },
    {
    'id':9,
    'nombre': "Limoncello",
    'precio': 275,
    'tipo': "digestivo",
    'imagen': "./imagenes/cocteles/limoncello.jpg",
    'origen': "Italia",
    'descripcion':"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, ratione?",
  },
    {
    'id':10,
    'nombre': "Margarita",
    'precio': 450,
    'tipo': "refrescante",
    'imagen': "./imagenes/cocteles/margarita.jpg",
    'origen': "Mexico",
    'descripcion':"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, sapiente.",
  },
    {
    'id':11,
    'nombre': "Daiquiri",
    'precio': 425,
    'tipo': "refrescante",
    'imagen': "./imagenes/cocteles/daiquiri.jpg",
    'origen': "Cuba",
    'descripcion':"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, amet.",
  },
    {
    'id':12,
    'nombre': "Mai Tai",
    'precio': 600,
    'tipo': "refrescante",
    'imagen': "./imagenes/cocteles/mai-tai.jpg",
    'origen': "Tahiti",
    'descripcion':"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, praesentium!",
  },
    {
    'id':13,
    'nombre': "Absenta",
    'precio': 500,
    'tipo': "chupito",
    'imagen': "./imagenes/cocteles/absenta.jpg",
    'origen': "Suiza",
    'descripcion':"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officia, vero.",
  },
    {
    'id':14,
    'nombre': "Jagermeister",
    'precio': 325,
    'tipo': "chupito",
    'imagen': "./imagenes/cocteles/jagermeister.jpg",
    'origen': "Alemania",
    'descripcion':"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed, aspernatur!",
  },
    {
    'id':15,
    'nombre': "Tequila",
    'precio': 200,
    'tipo': "chupito",
    'imagen': "./imagenes/cocteles/tequila.jpg",
    'origen': "Mexico",
    'descripcion':"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, consectetur.",
  },
    {
    'id':16,
    'nombre': "Cuba Libre",
    'precio': 150,
    'tipo': "popular",
    'imagen': "./imagenes/cocteles/cubalibre.jpg",
    'origen': "Cuba",
    'descripcion':"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae, eos!",
  },
    {
    'id':17,
    'nombre': "Gin Tonic",
    'precio': 150,
    'tipo': "popular",
    'imagen': "./imagenes/cocteles/gin-tonic.jpg",
    'origen': "India",
    'descripcion':"Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, necessitatibus.",
  },
    {
    'id':18,
    'nombre': "Pisco",
    'precio': 350,
    'tipo': "popular",
    'imagen': "./imagenes/cocteles/pisco.jpg",
    'origen': "Chile y Peru",
    'descripcion':"Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, beatae.",
  },
]